title: Manjaro Hyprland Edition Repository
email: info@manjaro-hyprland.download
url: "https://pkg.manjaro-hyprland.timesavior.io"
name: manjaro-hyprland

remote_theme: manjaro-hyprland/manjaro-hyprland

plugins:
  - jekyll-file-size
  - jekyll-webp

webp:
  enabled: true
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
safe: false