name: Build Jekyll and Deploy to Vercel

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.8

    - name: Install Bundler and Jekyll dependencies
      working-directory: docs
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      working-directory: docs
      run: |
        mkdir .vercel
        bundle exec jekyll build -d .vercel/output --safe false
        cp config.json .vercel/output

    - name: Test
      working-directory: docs
      run: |
        ls -la stable/x86_64/manjaro*

    - name: Install Vercel CLI
      run: npm i -g vercel

    - name: Deploy to Vercel
      run: |
        cd docs
        vercel deploy --token ${{ secrets.VERCEL_TOKEN }} --prebuilt --prod --scope manjaro-hyprland --yes
        #vercel --token ${{ secrets.VERCEL_TOKEN }} --cwd docs --scope manjaro-hyprland --prod --yes _site/
