name: Build Jekyll and Deploy to Vercel

on:
  workflow_dispatch:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.8

    - name: Install Bundler and Jekyll dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Install Vercel CLI
      run: npm i -g vercel

    - name: Deploy to Vercel
      run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod _site/
